# Generated by https://quicktype.io
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"

from enum import Enum
from typing import Optional, List


class DatumLinks:
    links_self: str
    plant: str
    genus: str

    def __init__(self, links_self: str, plant: str, genus: str) -> None:
        self.links_self = links_self
        self.plant = plant
        self.genus = genus


class Rank(Enum):
    SPECIES = "species"


class Status(Enum):
    ACCEPTED = "accepted"


class Datum:
    id: int
    common_name: str
    slug: str
    scientific_name: str
    year: int
    bibliography: str
    author: str
    status: Status
    rank: Rank
    family_common_name: Optional[str]
    genus_id: int
    image_url: str
    synonyms: List[str]
    genus: str
    family: str
    links: DatumLinks

    def __init__(self, id: int, common_name: str, slug: str, scientific_name: str, year: int, bibliography: str, author: str, status: Status, rank: Rank, family_common_name: Optional[str], genus_id: int, image_url: str, synonyms: List[str], genus: str, family: str, links: DatumLinks) -> None:
        self.id = id
        self.common_name = common_name
        self.slug = slug
        self.scientific_name = scientific_name
        self.year = year
        self.bibliography = bibliography
        self.author = author
        self.status = status
        self.rank = rank
        self.family_common_name = family_common_name
        self.genus_id = genus_id
        self.image_url = image_url
        self.synonyms = synonyms
        self.genus = genus
        self.family = family
        self.links = links


class OutLinks:
    links_self: str
    first: str
    next: str
    last: str

    def __init__(self, links_self: str, first: str, next: str, last: str) -> None:
        self.links_self = links_self
        self.first = first
        self.next = next
        self.last = last


class Meta:
    total: int

    def __init__(self, total: int) -> None:
        self.total = total


class Out:
    data: List[Datum]
    links: OutLinks
    meta: Meta

    def __init__(self, data: List[Datum], links: OutLinks, meta: Meta) -> None:
        self.data = data
        self.links = links
        self.meta = meta
